### ISSUE TITLE
Registering the service and setting it as the authenticator should come last.

### ISSUE THREAD

**Issue by nesl247** [knpuniversity/guard-tutorial#3]
In the API Token tutorial, you register the service and authenticator before you actually implement the service. This seems a little backwards considering the authenticator isn't in a usable state yet. If you look at any of the Symfony tutorials, that part always comes last, because it's the last logical step.

**Comment by weaverryan** [comment]
I have a chicken-and-egg problem. To finish the configurator, I need to who what we've got in the `__construct()`. And when I show the `__construct()` (with its args), that seems like the best time to show the `services.yml` setup. But I can see it your way - e.g. "Here's the constructor - we need the EntityManager"... then WAY later "since the __construct() method needs the entity manager, we're adding it here as an argument in services.yml"
